{% set name = "respx" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c792e2bb5b70deda5f6c1be460c1e524cd6d2eea4240a38e973341c1ea211c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpx >=0.18
    - python >=3.6

test:
  imports:
    - respx

about:
  home: https://lundberg.github.io/respx
  summary: A utility for mocking out the Python HTTPX library.
  license: BSD-3-Clause
  license_file: LICENSE.md
  dev_url: https://github.com/lundberg/respx
  doc_url: https://lundberg.github.io/respx

extra:
  recipe-maintainers:
    - synapticarbors
