{% set name = "respx" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c8924caa2a50bd71aefc07aa812f2466ff489f1848c96e954a5362d17095d91

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - httpx >=0.25.0
    - python >=3.7

test:
  imports:
    - respx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://lundberg.github.io/respx
  summary: A utility for mocking out the Python HTTPX library.
  license: BSD-3-Clause
  license_file: LICENSE.md
  dev_url: https://github.com/lundberg/respx
  doc_url: https://lundberg.github.io/respx

extra:
  recipe-maintainers:
    - synapticarbors
