{% set name = "respx" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7bf8369f4caeb494b424291617f0d26d3f64b3cab4b47f8aac25e034ff3526c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asynctest
    - httpx <0.13,>=0.12
    - python >=3.6

test:
  imports:
    - respx

about:
  home: https://lundberg.github.io/respx
  summary: A utility for mocking out the Python HTTPX library.
  license: BSD-3-Clause
  # Manually packaged: https://github.com/lundberg/respx/pull/48
  license_file: LICENSE.md
  dev_url: https://github.com/lundberg/respx
  doc_url: https://lundberg.github.io/respx

extra:
  recipe-maintainers:
    - synapticarbors
